name: Deploy Static Website to Production EC2

on:
  push:
    branches:
      - main    # When developer pushes code to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/prod_key
        chmod 600 ~/.ssh/prod_key

    - name: Copy files to Production EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/prod_key -r * ec2-user@54.226.173.229:/tmp/app

    - name: Deploy on Production EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/prod_key ec2-user@54.226.173.229 "
          sudo rm -rf /var/www/html/* &&
          sudo mkdir -p /var/www/html &&
          sudo cp -r /tmp/app/* /var/www/html/ &&
          sudo systemctl restart httpd || sudo systemctl restart apache2
        "
